import type { Mesa, FilaCliente, Funcionario, ConfiguracoesFila, HistoricoAtendimento } from '../types';


export const mockRestauranteId = 'rest-123';

export const initialFuncionarios: Funcionario[] = [
  { id: 'f-1', nome: 'Clara Santos', cargo: 'recepcao', permissao: ['fila', 'chamados'] },
  { id: 'f-2', nome: 'Felipe Souza', cargo: 'garcom', permissao: ['mesas'] },
  { id: 'f-3', nome: 'Renato Silva', cargo: 'admin', permissao: ['all'] },
];

export const initialConfiguracoesFila: ConfiguracoesFila = {
  permitir2em4: true,
  permitir4em6: true,
  permitir6em8: true,
  diferencaMaximaGrupoMesa: 2,
  tempoToleranciaChamadoMinutos: 5,
};

// Helper for generating relative times in ISO format
const getRelativeTimeISO = (minutesAgo: number): string => {
  const date = new Date();
  date.setMinutes(date.getMinutes() - minutesAgo);
  return date.toISOString();
};

export const initialMesas: Mesa[] = [
  {
    id: 'm-1',
    restaurante_id: mockRestauranteId,
    numero_mesa: '1',
    nome_ou_identificacao: 'Mesa 1',
    capacidade_maxima: 2,
    capacidade_ideal: 2,
    status_atual: 'livre',
    setor_ou_area: 'Interno',
    observacoes: 'Perto da janela',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(10),
  },
  {
    id: 'm-2',
    restaurante_id: mockRestauranteId,
    numero_mesa: '2',
    nome_ou_identificacao: 'Mesa 2',
    capacidade_maxima: 2,
    capacidade_ideal: 2,
    status_atual: 'ocupada',
    setor_ou_area: 'Interno',
    observacoes: '',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(45),
  },
  {
    id: 'm-3',
    restaurante_id: mockRestauranteId,
    numero_mesa: '3',
    nome_ou_identificacao: 'Mesa 3',
    capacidade_maxima: 4,
    capacidade_ideal: 4,
    status_atual: 'livre',
    setor_ou_area: 'Varanda',
    observacoes: 'Vista para a praça',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(15),
  },
  {
    id: 'm-4',
    restaurante_id: mockRestauranteId,
    numero_mesa: '4',
    nome_ou_identificacao: 'Mesa 4',
    capacidade_maxima: 4,
    capacidade_ideal: 4,
    status_atual: 'ocupada',
    setor_ou_area: 'Interno',
    observacoes: '',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(80),
  },
  {
    id: 'm-5',
    restaurante_id: mockRestauranteId,
    numero_mesa: '5',
    nome_ou_identificacao: 'Mesa 5',
    capacidade_maxima: 4,
    capacidade_ideal: 4,
    status_atual: 'conta_solicitada',
    setor_ou_area: 'Varanda',
    observacoes: '',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(5),
  },
  {
    id: 'm-6',
    restaurante_id: mockRestauranteId,
    numero_mesa: '6',
    nome_ou_identificacao: 'Mesa 6',
    capacidade_maxima: 6,
    capacidade_ideal: 6,
    status_atual: 'em_pagamento',
    setor_ou_area: 'Terraço',
    observacoes: 'Sofá grande',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(5),
  },
  {
    id: 'm-7',
    restaurante_id: mockRestauranteId,
    numero_mesa: '7',
    nome_ou_identificacao: 'Mesa 7',
    capacidade_maxima: 6,
    capacidade_ideal: 6,
    status_atual: 'em_preparo',
    setor_ou_area: 'Terraço',
    observacoes: 'Precisa limpar banco',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(2),
  },
  {
    id: 'm-8',
    restaurante_id: mockRestauranteId,
    numero_mesa: '8',
    nome_ou_identificacao: 'Mesa 8',
    capacidade_maxima: 8,
    capacidade_ideal: 8,
    status_atual: 'livre',
    setor_ou_area: 'Interno',
    observacoes: 'Mesa Família',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(30),
  },
  {
    id: 'm-9',
    restaurante_id: mockRestauranteId,
    numero_mesa: '9',
    nome_ou_identificacao: 'Mesa 9',
    capacidade_maxima: 2,
    capacidade_ideal: 2,
    status_atual: 'reservada',
    setor_ou_area: 'Varanda',
    observacoes: 'Reserva para as 20h',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(120),
  },
  {
    id: 'm-10',
    restaurante_id: mockRestauranteId,
    numero_mesa: '10',
    nome_ou_identificacao: 'Mesa 10',
    capacidade_maxima: 4,
    capacidade_ideal: 4,
    status_atual: 'pronta',
    setor_ou_area: 'Interno',
    observacoes: 'Recém limpa e organizada',
    criado_em: getRelativeTimeISO(200),
    atualizado_em: getRelativeTimeISO(1),
  },
];

export const initialFilaClientes: FilaCliente[] = [
  {
    id: 'c-1',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'João Silva',
    whatsapp: '11999998888',
    quantidade_pessoas: 4,
    observacoes: 'Cadeirante, área interna',
    status: 'aguardando',
    horario_entrada: getRelativeTimeISO(35),
    criado_em: getRelativeTimeISO(35),
    atualizado_em: getRelativeTimeISO(35),
  },
  {
    id: 'c-2',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Maria Souza',
    whatsapp: '11988887777',
    quantidade_pessoas: 2,
    observacoes: 'Criança (precisa de cadeirão), varanda',
    status: 'aguardando',
    horario_entrada: getRelativeTimeISO(25),
    criado_em: getRelativeTimeISO(25),
    atualizado_em: getRelativeTimeISO(25),
  },
  {
    id: 'c-3',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Pedro Santos',
    whatsapp: '11977776666',
    quantidade_pessoas: 6,
    observacoes: 'Área externa/Varanda preferencialmente',
    status: 'aguardando',
    horario_entrada: getRelativeTimeISO(15),
    criado_em: getRelativeTimeISO(15),
    atualizado_em: getRelativeTimeISO(15),
  },
  {
    id: 'c-4',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Ana Oliveira',
    whatsapp: '11966665555',
    quantidade_pessoas: 2,
    observacoes: 'Preferência interna',
    status: 'chamado',
    horario_entrada: getRelativeTimeISO(45),
    horario_chamada: getRelativeTimeISO(4),
    mesa_destinada_id: 'm-10',
    numero_mesa_destinada: '10',
    criado_em: getRelativeTimeISO(45),
    atualizado_em: getRelativeTimeISO(4),
  },
  {
    id: 'c-5',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Carlos Lima',
    whatsapp: '11955554444',
    quantidade_pessoas: 3,
    observacoes: 'Carrinho de bebê',
    status: 'chegou',
    horario_entrada: getRelativeTimeISO(30),
    horario_chamada: getRelativeTimeISO(10),
    horario_chegada_recepcao: getRelativeTimeISO(2),
    mesa_destinada_id: 'm-3',
    numero_mesa_destinada: '3',
    criado_em: getRelativeTimeISO(30),
    atualizado_em: getRelativeTimeISO(2),
  },
  {
    id: 'c-6',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Mariana Costa',
    whatsapp: '11944443333',
    quantidade_pessoas: 5,
    observacoes: '',
    status: 'cancelado',
    horario_entrada: getRelativeTimeISO(60),
    criado_em: getRelativeTimeISO(60),
    atualizado_em: getRelativeTimeISO(40),
  },
  {
    id: 'c-7',
    restaurante_id: mockRestauranteId,
    nome_cliente: 'Roberto Dias',
    whatsapp: '11933332222',
    quantidade_pessoas: 2,
    observacoes: '',
    status: 'ausente',
    horario_entrada: getRelativeTimeISO(50),
    criado_em: getRelativeTimeISO(50),
    atualizado_em: getRelativeTimeISO(35),
  },
];

export const initialHistoricoAtendimentos: HistoricoAtendimento[] = [
  {
    id: 'h-1',
    cliente_id: 'c-101',
    mesa_id: 'm-1',
    numero_mesa: '1',
    quantidade_pessoas: 2,
    horario_entrada_fila: getRelativeTimeISO(120),
    horario_chamada: getRelativeTimeISO(100),
    horario_sentou: getRelativeTimeISO(95),
    tempo_total_espera: 25,
    status_final: 'atendido',
  },
  {
    id: 'h-2',
    cliente_id: 'c-102',
    mesa_id: 'm-4',
    numero_mesa: '4',
    quantidade_pessoas: 4,
    horario_entrada_fila: getRelativeTimeISO(180),
    horario_chamada: getRelativeTimeISO(140),
    horario_sentou: getRelativeTimeISO(138),
    tempo_total_espera: 42,
    status_final: 'atendido',
  },
  {
    id: 'h-3',
    cliente_id: 'c-103',
    mesa_id: 'm-8',
    numero_mesa: '8',
    quantidade_pessoas: 7,
    horario_entrada_fila: getRelativeTimeISO(210),
    horario_chamada: getRelativeTimeISO(170),
    horario_sentou: getRelativeTimeISO(165),
    tempo_total_espera: 45,
    status_final: 'atendido',
  },
];
